version: '3.9'

services:
  db:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: tascom
      POSTGRES_PASSWORD: tascomteste
      POSTGRES_DB: tascom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: